# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

services:
  flink-job-mgr:
    build:
      context: flink
    container_name: docker-flink-job-mgr_${PROJECT_NAME}
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ${CACHE_DIR}/maven:/opt/flink/app
    environment:
      # Flink Configuration
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-job-mgr"
    networks:
      - flink-net
    command: jobmanager

  flink-task-mgr:
    build:
      context: flink
    container_name: docker-flink-task-mgr_${PROJECT_NAME}
    restart: always
    environment:
      # Flink Configuration
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-job-mgr
        taskmanager.numberOfTaskSlots: 2
    networks:
      - flink-net
    command: taskmanager

  maven:
    build:
      context: maven
    container_name: docker-java-maven_${PROJECT_NAME}
    volumes:
      - ${CACHE_DIR}/maven:/cache
      - ${APP_DIR}/maven:/app
    working_dir: /app

networks:
  flink-net:
    driver: bridge
